[package]
name = "algebra-utils"
version = "0.1.0"
authors = [
    "Sean Bowe",
    "Alessandro Chiesa",
    "Matthew Green",
    "Ian Miers",
    "Pratyush Mishra",
    "Howard Wu",
    "Daniele Di Benedetto <daniele@horizenlabs.io>",
    "Marcelo Kaihara <marcelo@horizenlabs.io>",
    "Ulrich Haboeck <ulrich@horizenlabs.io>"
]
description = "A library for finite fields, elliptic curves and FFTs evaluation over prime finite fields"
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

################################# Dependencies ################################

[dependencies]
algebra = { path = "../algebra", features = [ "parallel" ] }

rand = { version = "0.7" }

rayon = { version = "1", optional = true }

# gpu feature
algebra-kernels = { path = "../../ginger-algebra-ocl/algebra-kernels", optional = true }
algebra-cl-gen = { path = "../../ginger-algebra-ocl/algebra-cl-gen", optional = true }
crossbeam = { version = "0.7", optional = true }

[dev-dependencies]
blake2 = "0.7"
criterion = "0.2"
rand_xorshift = { version = "0.2" }
paste = "1.0"
algebra = { path = "../algebra", features = ["bls12_381", "jubjub", "mnt4_753", "mnt6_753"] }
algebra-utils = { path = "../algebra-utils", features = [ "parallel", "fft" ] }
algebra-kernels = { path = "../../ginger-algebra-ocl/algebra-kernels", features = ["bls12_381", "jubjub"] }

[features]
parallel = [ "rayon" ]
fft = []
gpu = [ "algebra-kernels", "bellperson", "crossbeam" ]

[build-dependencies]
rustc_version = "0.2"